### ISSUE TITLE
Loosing Datapoints

### ISSUE THREAD

**Issue by benidroe** [influxdb/influxdb-java#78] opened 2015-08-15 12:20 UTC
Hey,

I´m trying to write Datapoints from Networkswitches collected via SNMP to influxdb. Cause my network is verry large I have many Threads for SNMP. The SNMP Threads writes to a BlockingQueue. My database writer thread takesPoints from the queue and write them the InfluxDB batch. 

My problem is: Points get lost while writing. The Points are definely taken from my BlockingQueue.

Here my DatabaseWriter class:

    public class DatabaseWriter implements Runnable {

    private String dbName = "Monitoring";

    InfluxDB influxDB;

    public DatabaseWriter() {

    }

    @Override
    public void run() {
    
        this.influxDB = InfluxDBFactory.connect("http://x.x.x.x:8086", "uuuu", "ppppp");
        influxDB.createDatabase(dbName);
        // Flush every 2000 Points, at least every 100ms
        influxDB.enableBatch(2000, 100, TimeUnit.MILLISECONDS);
        influxDB.setLogLevel(InfluxDB.LogLevel.FULL);

        try{
        Point p;
            while (true){

                p = (Point) Collector.writeQueue.take();
                influxDB.write(dbName, "default", p);
                System.out.println("written");

            }
        } catch (InterruptedException e){
            System.out.println("Can´t take element from queue " + e);
        }

    }
    }

**Comment by caoli5288** [comment] 2015-08-15 14:52
How 'd you find points got lost?

**Comment by benidroe** [comment] 2015-08-16 11:39
I´ve generated test-points and made sysouts at some positions in my code. Only in my influxdb these points didn´t appear.

**Comment by majst01** [comment] 2015-08-19 00:00
I still cannot see how you identify that datapoints are missing.

The Batch Mode only commits after 2000 points or 100ms whatever occurs first. So there can always be 1999 points on the way to influxdb !

To nail down please show some tests which cleary show the problem.

**Comment by majst01** [comment] 2015-09-07 11:36
May i close this issue ?

**Comment by sadhip3** [comment] 2015-09-10 22:18
Looks like this particular step :Query query = new Query("SELECT idle FROM cpu", dbName); gives me the following result : QueryResult [results=[Result [series=null, error=null]], error=null] . When i do a select * from cpu in my local influxdb i get a success but no result. Could it be related to the inflexdb configuration i have ??

**Comment by majst01** [comment] 2015-09-11 05:42
So it seem you do not have any datapoints stored in cpu.

**Comment by sadhip3** [comment] 2015-09-11 14:35
I am using the exact code you have given in the example ... That writes a measurement called cpu and  when i do a get on it i don't see a value. I have used the same code you have given in the example and i am adding the points to batchpoint as given below and writing the batch point. This should have written a point called cpu right. Can you give me any ideas how i can figure out where i am going wrong ... why datapoints are not getting stored in cpu. 

  batchPoints.point(point1);
  batchPoints.point(point2);
  influxDB.write(batchPoints);

**Comment by hkrizek** [comment] 2015-09-15 13:22
I have probably similar issue. I'm trying to write points with this super simple code:
```
        BatchPoints batchPoints = BatchPoints
                .database(dbName)
                .tag("async", "true")
                .retentionPolicy("default")
                .consistency(InfluxDB.ConsistencyLevel.ALL)
                .build();
        for(int i = 1; i <= 1000; i++) {
            Point point1 = Point.measurement("cpuBatch")
                    .time(System.currentTimeMillis(), TimeUnit.MILLISECONDS)
                    .field("idle", i).field("system", 10 * i)
                    .build();
            batchPoints.point(point1);
        }
        influxDB.write(batchPoints);
```
and the result is that there are stored something among 8-15 points instead of 1000.
When I did tcpdump it seems that all 1000 measurements come to influxdb server.

Influxdb version 0.9.3
influxdb-java built from master (I have to comment testWrite method in InfluxDBTest, it is not able to compile)

**Comment by pgoudreau** [comment] 2015-09-17 14:00
We were missing points as well. It turns out that we were sending multiple points with the same timestamp and InfluxDB was overwriting the  old points.

**Comment by hkrizek** [comment] 2015-09-21 12:52
@pgoudreau you are right, there were points with same timestamps. 
I tried another case without line .time(System.currentTimeMillis(), TimeUnit.MILLISECONDS) expected that InfluxDB will insert the correct time itself, but influxdb-java set time if it is not defined and this leads to the same issue. points have the same timestamps.

**Comment by pgoudreau** [comment] 2015-09-21 13:12
@hkrizek our solution is not ideal but we use the nanosecond space to make sure that points are unique.

**Comment by benidroe** [comment] 2015-09-21 15:50
Is it possible to use tags to make datapoints unique? E.g. to putting differend CPUs into different series?

**Comment by pgoudreau** [comment] 2015-09-21 16:03
In influxDB each point is uniquely identified by its measurement and time.

**Comment by benidroe** [comment] 2015-09-21 16:10
I try to collect datatransferrates from every switchport in my network. So I have thousands of datapoints with the same time and value = 0. How can I make these points unique? If they get lost it´s a little bit impractical. Is there any structure you can recommend to me?

**Comment by pgoudreau** [comment] 2015-09-21 17:54
Since v0.9.0-rc4 tags can make points unique from InfluxDB [blog](https://influxdb.com/blog/2015/02/24/influxdb-v0_9_0-rc4_released_now_with_tags_and_more_unicorns.html)

**Comment by majst01** [comment] 2015-10-01 07:24
It seems consens that this is caused by same points written to influxdb, closing this issue now.

**Closed by majst01** 2015-10-01 07:24 UTC
