### ISSUE TITLE
getting 'bad timestamp' exception

### ISSUE THREAD

**Issue by haninaguib** [influxdb/influxdb-java#40] opened 2015-06-25 17:40 UTC
Anyone know what may cause the following exception?
java.lang.RuntimeException: bad timestamp
	at org.influxdb.impl.InfluxDBErrorHandler.handleError(InfluxDBErrorHandler.java:19)
	at retrofit.RestAdapter$RestHandler.invoke(RestAdapter.java:242)
	at org.influxdb.impl.$Proxy58.writePoints(Unknown Source)
	at org.influxdb.impl.InfluxDBImpl.write(InfluxDBImpl.java:150)

relevant code:
        long time = System.currentTimeMillis();
        BatchPoints points = BatchPoints.database(dbName).time(time, TimeUnit.MILLISECONDS).tag("async", "true").retentionPolicy("default")
                .consistency(ConsistencyLevel.ALL).build();

and in a loop

                Point point = Point.measurement(entry.getKey()).field("value", value).time(time, TimeUnit.MILLISECONDS).build();
                points.point(point);

at the end
            db.write(points);

**Comment by majst01** [comment] 2015-06-25 17:57
Hi,

this is duplicate of #38 
Im already fixing this, its related to spaces, commas and other special characters in keys and or values of fields and tags. 

I close this ticket.
Stefan

**Closed by majst01** 2015-06-25 17:57 UTC
