### ISSUE TITLE
documentation of batching and NullPointerException

### ISSUE THREAD

**Issue by BernhardRiedhofer** [influxdb/influxdb-java#41] opened 2015-06-26 14:24 UTC
The page where sources for batching is described contains wrong source code:
https://github.com/influxdb/influxdb-java

is:
should be:

is: 
influxDB.write(point1);
influxDB.write(point1);

should be: 
influxDB.write(dbName, retentionPolicy, point1);
influxDB.write(dbName, retentionPolicy, point2);

However with these code changes a NullPointerException happens:
Caused by: java.lang.NullPointerException: while trying to invoke the method java.util.concurrent.TimeUni
t.ordinal() of a null object loaded from local variable 't'
at org.influxdb.impl.TimeUtil.toTimePrecision(TimeUtil.java:21)
at org.influxdb.impl.InfluxDBImpl.write(InfluxDBImpl.java:150)
at org.influxdb.impl.BatchProcessor.write(BatchProcessor.java:164)
at org.influxdb.impl.BatchProcessor.put(BatchProcessor.java:179)
at org.influxdb.impl.InfluxDBImpl.write(InfluxDBImpl.java:136)

**Comment by majst01** [comment] 2015-06-27 12:16
Hi Bernhard,

thanks for pointing out the error in the usage example. I fixed this in 0dcf3668b3925cba71faf1b557e1cdd80be46363 as well added a Test for your use case an to be honest i cant reproduce it.

https://github.com/influxdb/influxdb-java/blob/0dcf3668b3925cba71faf1b557e1cdd80be46363/src/test/java/org/influxdb/TicketTests.java#L136

Can you please show me a reproducer ?

Greetings
Stefan

**Comment by BernhardRiedhofer** [comment] 2015-06-28 06:19
Hi Stefan,

Thanks for fixing the documentation!

I tried to reproduce but InfluxDB is constantly crashing now. Could this be the reason?

Regards,
Bernhard




2015/06/28 06:05:44 [INFO] snapshot: Creating new snapshot at /var/opt/influxdb/meta/snapshots/2-8388-1435471544599.tmp
panic: not implemented yet

goroutine 12 [running]:
github.com/influxdb/influxdb/meta.(*storeFSMSnapshot).Persist(0xc20a2a4338, 0x7f952bfd5430, 0xc20804aaa0, 0x0, 0x0)
        /root/.gvm/pkgsets/go1.4.2/global/src/github.com/influxdb/influxdb/meta/store.go:1592 +0x76
github.com/hashicorp/raft.(*Raft).takeSnapshot(0xc2080b61c0, 0x0, 0x0)
        /root/.gvm/pkgsets/go1.4.2/global/src/github.com/hashicorp/raft/raft.go:1674 +0x826
github.com/hashicorp/raft.(*Raft).runSnapshots(0xc2080b61c0)
        /root/.gvm/pkgsets/go1.4.2/global/src/github.com/hashicorp/raft/raft.go:1602 +0x105
github.com/hashicorp/raft.*Raft.(github.com/hashicorp/raft.runSnapshots)·fm()
        /root/.gvm/pkgsets/go1.4.2/global/src/github.com/hashicorp/raft/raft.go:243 +0x27
github.com/hashicorp/raft.func·011()
        /root/.gvm/pkgsets/go1.4.2/global/src/github.com/hashicorp/raft/state.go:152 +0x51
created by github.com/hashicorp/raft.(*raftState).goFunc
        /root/.gvm/pkgsets/go1.4.2/global/src/github.com/hashicorp/raft/state.go:153 +0xe3

goroutine 1 [chan receive (nil chan), 1 minutes]:
main.(*Main).Run(0xc20a428f60, 0xc20800a010, 0x4, 0x4, 0x0, 0x0)
        /root/.gvm/pkgsets/go1.4.2/global/src/github.com/influxdb/influxdb/cmd/influxd/main.go:81 +0x450
main.main()
        /root/.gvm/pkgsets/go1.4.2/global/src/github.com/influxdb/influxdb/cmd/influxd/main.go:39 +0x1d0

goroutine 6 [syscall, 3 minutes]:
os/signal.loop()
        /root/.gvm/gos/go1.4.2/src/os/signal/signal_unix.go:21 +0x1f
created by os/signal.init·1
        /root/.gvm/gos/go1.4.2/src/os/signal/signal_unix.go:27 +0x35

goroutine 50 [select]:
github.com/influxdb/influxdb/services/hh.(*Service).retryWrites(0xc20804b2c0)
        /root/.gvm/pkgsets/go1.4.2/global/src/github.com/influxdb/influxdb/services/hh/service.go:98 +0x2e7
created by github.com/influxdb/influxdb/services/hh.(*Service).Open
        /root/.gvm/pkgsets/go1.4.2/global/src/github.com/influxdb/influxdb/services/hh/service.go:62 +0xef

goroutine 17 [syscall, 2 minutes, locked to thread]:
runtime.goexit()
        /root/.gvm/gos/go1.4.2/src/runtime/asm_amd64.s:2232 +0x1

goroutine 8 [IO wait, 2 minutes]:
net.(*pollDesc).Wait(0xc20800c450, 0x72, 0x0, 0x0)
        /root/.gvm/gos/go1.4.2/src/net/fd_poll_runtime.go:84 +0x47
net.(*pollDesc).WaitRead(0xc20800c450, 0x0, 0x0)
        /root/.gvm/gos/go1.4.2/src/net/fd_poll_runtime.go:89 +0x43
net.(*netFD).accept(0xc20800c3f0, 0x0, 0x7f954b881cc8, 0xc2080ea000)
        /root/.gvm/gos/go1.4.2/src/net/fd_unix.go:419 +0x40b
net.(*TCPListener).AcceptTCP(0xc2080367c8, 0x0, 0x0, 0x0)
        /root/.gvm/gos/go1.4.2/src/net/tcpsock_posix.go:234 +0x4e
net.(*TCPListener).Accept(0xc2080367c8, 0x0, 0x0, 0x0, 0x0)
        /root/.gvm/gos/go1.4.2/src/net/tcpsock_posix.go:244 +0x4c
github.com/influxdb/influxdb/tcp.(*Mux).Serve(0xc2080b9bc0, 0x7f954b884110, 0xc2080367c8, 0x0, 0x0)
        /root/.gvm/pkgsets/go1.4.2/global/src/github.com/influxdb/influxdb/tcp/mux.go:45 +0x57
created by github.com/influxdb/influxdb/cmd/influxd/run.func·003
        /root/.gvm/pkgsets/go1.4.2/global/src/github.com/influxdb/influxdb/cmd/influxd/run/server.go:274 +0x762

goroutine 9 [chan receive, 2 minutes]:
github.com/influxdb/influxdb/tcp.(*listener).Accept(0xc2080367d0, 0x0, 0x0, 0x0, 0x0)
        /root/.gvm/pkgsets/go1.4.2/global/src/github.com/influxdb/influxdb/tcp/mux.go:117 +0x80
github.com/influxdb/influxdb/meta.(*raftLayer).Accept(0xc2080b9bf0, 0x0, 0x0, 0x0, 0x0)
        /root/.gvm/pkgsets/go1.4.2/global/src/github.com/influxdb/influxdb/meta/store.go:1636 +0x64
github.com/hashicorp/raft.(*NetworkTransport).listen(0xc20800c4d0)
        /root/.gvm/pkgsets/go1.4.2/global/src/github.com/hashicorp/raft/net_transport.go:346 +0x50
created by github.com/hashicorp/raft.NewNetworkTransport
        /root/.gvm/pkgsets/go1.4.2/global/src/github.com/hashicorp/raft/net_transport.go:138 +0x2c4

goroutine 10 [select]:
github.com/hashicorp/raft.(*Raft).leaderLoop(0xc2080b61c0)
        /root/.gvm/pkgsets/go1.4.2/global/src/github.com/hashicorp/raft/raft.go:807 +0xc7c
github.com/hashicorp/raft.(*Raft).runLeader(0xc2080b61c0)
        /root/.gvm/pkgsets/go1.4.2/global/src/github.com/hashicorp/raft/raft.go:779 +0x74e
github.com/hashicorp/raft.(*Raft).run(0xc2080b61c0)
       /root/.gvm/pkgsets/go1.4.2/global/src/github.com/hashicorp/raft/raft.go:576 +0xc9
github.com/hashicorp/raft.*Raft.(github.com/hashicorp/raft.run)·fm()
        /root/.gvm/pkgsets/go1.4.2/global/src/github.com/hashicorp/raft/raft.go:241 +0x27
github.com/hashicorp/raft.func·011()
        /root/.gvm/pkgsets/go1.4.2/global/src/github.com/hashicorp/raft/state.go:152 +0x51
created by github.com/hashicorp/raft.(*raftState).goFunc
        /root/.gvm/pkgsets/go1.4.2/global/src/github.com/hashicorp/raft/state.go:153 +0xe3

goroutine 11 [select]:
github.com/hashicorp/raft.(*Raft).runFSM(0xc2080b61c0)
        /root/.gvm/pkgsets/go1.4.2/global/src/github.com/hashicorp/raft/raft.go:490 +0xf74
github.com/hashicorp/raft.*Raft.(github.com/hashicorp/raft.runFSM)·fm()
        /root/.gvm/pkgsets/go1.4.2/global/src/github.com/hashicorp/raft/raft.go:242 +0x27
github.com/hashicorp/raft.func·011()
        /root/.gvm/pkgsets/go1.4.2/global/src/github.com/hashicorp/raft/state.go:152 +0x51
created by github.com/hashicorp/raft.(*raftState).goFunc
        /root/.gvm/pkgsets/go1.4.2/global/src/github.com/hashicorp/raft/state.go:153 +0xe3

goroutine 18 [chan receive, 2 minutes]:
github.com/influxdb/influxdb/tcp.(*listener).Accept(0xc2080367d8, 0x0, 0x0, 0x0, 0x0)
        /root/.gvm/pkgsets/go1.4.2/global/src/github.com/influxdb/influxdb/tcp/mux.go:117 +0x80
github.com/influxdb/influxdb/meta.(*Store).serveExecListener(0xc208070000)
        /root/.gvm/pkgsets/go1.4.2/global/src/github.com/influxdb/influxdb/meta/store.go:436 +0x8f
created by github.com/influxdb/influxdb/meta.(*Store).Open
        /root/.gvm/pkgsets/go1.4.2/global/src/github.com/influxdb/influxdb/meta/store.go:183 +0x1c2

goroutine 34 [select, 2 minutes]:
github.com/influxdb/influxdb/cmd/influxd/run.(*Server).monitorErrorChan(0xc20802e000, 0xc2080443c0)
        /root/.gvm/pkgsets/go1.4.2/global/src/github.com/influxdb/influxdb/cmd/influxd/run/server.go:390 +0x14a
created by github.com/influxdb/influxdb/cmd/influxd/run.func·003
        /root/.gvm/pkgsets/go1.4.2/global/src/github.com/influxdb/influxdb/cmd/influxd/run/server.go:280 +0x8d3

goroutine 51 [select, 1 minutes]:
github.com/influxdb/influxdb/services/hh.(*Service).expireWrites(0xc20804b2c0)
        /root/.gvm/pkgsets/go1.4.2/global/src/github.com/influxdb/influxdb/services/hh/service.go:116 +0x2a4
created by github.com/influxdb/influxdb/services/hh.(*Service).Open
        /root/.gvm/pkgsets/go1.4.2/global/src/github.com/influxdb/influxdb/services/hh/service.go:63 +0x109

goroutine 52 [chan receive, 1 minutes]:
github.com/influxdb/influxdb/tcp.(*listener).Accept(0xc2080367e0, 0x0, 0x0, 0x0, 0x0)
        /root/.gvm/pkgsets/go1.4.2/global/src/github.com/influxdb/influxdb/tcp/mux.go:117 +0x80
github.com/influxdb/influxdb/cluster.(*Service).serve(0xc20800c2a0)
        /root/.gvm/pkgsets/go1.4.2/global/src/github.com/influxdb/influxdb/cluster/service.go:79 +0x102
created by github.com/influxdb/influxdb/cluster.(*Service).Open
        /root/.gvm/pkgsets/go1.4.2/global/src/github.com/influxdb/influxdb/cluster/service.go:56 +0x67

goroutine 53 [select, 1 minutes]:
github.com/influxdb/influxdb/services/precreator.(*Service).runPrecreation(0xc20800ad70)
        /root/.gvm/pkgsets/go1.4.2/global/src/github.com/influxdb/influxdb/services/precreator/service.go:72 +0x407
created by github.com/influxdb/influxdb/services/precreator.(*Service).Open
        /root/.gvm/pkgsets/go1.4.2/global/src/github.com/influxdb/influxdb/services/precreator/service.go:50 +0xcb

goroutine 54 [chan receive, 1 minutes]:
github.com/influxdb/influxdb/tcp.(*listener).Accept(0xc2080367e8, 0x0, 0x0, 0x0, 0x0)
        /root/.gvm/pkgsets/go1.4.2/global/src/github.com/influxdb/influxdb/tcp/mux.go:117 +0x80
github.com/influxdb/influxdb/services/snapshotter.(*Service).serve(0xc20800ae60)
        /root/.gvm/pkgsets/go1.4.2/global/src/github.com/influxdb/influxdb/services/snapshotter/service.go:68 +0xad
created by github.com/influxdb/influxdb/services/snapshotter.(*Service).Open
        /root/.gvm/pkgsets/go1.4.2/global/src/github.com/influxdb/influxdb/services/snapshotter/service.go:46 +0x62

goroutine 55 [IO wait, 1 minutes]:
net.(*pollDesc).Wait(0xc2081280d0, 0x72, 0x0, 0x0)
        /root/.gvm/gos/go1.4.2/src/net/fd_poll_runtime.go:84 +0x47
net.(*pollDesc).WaitRead(0xc2081280d0, 0x0, 0x0)
        /root/.gvm/gos/go1.4.2/src/net/fd_poll_runtime.go:89 +0x43
net.(*netFD).accept(0xc208128070, 0x0, 0x7f954b881cc8, 0xc20a432040)
        /root/.gvm/gos/go1.4.2/src/net/fd_unix.go:419 +0x40b
net.(*TCPListener).AcceptTCP(0xc2085b81e0, 0xc208056380, 0x0, 0x0)
        /root/.gvm/gos/go1.4.2/src/net/tcpsock_posix.go:234 +0x4e
net.(*TCPListener).Accept(0xc2085b81e0, 0x0, 0x0, 0x0, 0x0)
        /root/.gvm/gos/go1.4.2/src/net/tcpsock_posix.go:244 +0x4c
net/http.(*Server).Serve(0xc208e18180, 0x7f954b884110, 0xc2085b81e0, 0x0, 0x0)
        /root/.gvm/gos/go1.4.2/src/net/http/server.go:1728 +0x92
net/http.Serve(0x7f954b884110, 0xc2085b81e0, 0x7f952bfd41e8, 0xc20a432030, 0x0, 0x0)
        /root/.gvm/gos/go1.4.2/src/net/http/server.go:1606 +0xa1
github.com/influxdb/influxdb/services/admin.(*Service).serve(0xc2080b99e0)
        /root/.gvm/pkgsets/go1.4.2/global/src/github.com/influxdb/influxdb/services/admin/service.go:71 +0x147
created by github.com/influxdb/influxdb/services/admin.(*Service).Open
        /root/.gvm/pkgsets/go1.4.2/global/src/github.com/influxdb/influxdb/services/admin/service.go:39 +0xd9

goroutine 56 [select]:
github.com/influxdb/influxdb/services/continuous_querier.(*Service).backgroundLoop(0xc20800c310)
        /root/.gvm/pkgsets/go1.4.2/global/src/github.com/influxdb/influxdb/services/continuous_querier/service.go:151 +0x1fc
created by github.com/influxdb/influxdb/services/continuous_querier.(*Service).Open
        /root/.gvm/pkgsets/go1.4.2/global/src/github.com/influxdb/influxdb/services/continuous_querier/service.go:87 +0x1ed

goroutine 57 [IO wait, 1 minutes]:
net.(*pollDesc).Wait(0xc208128140, 0x72, 0x0, 0x0)
        /root/.gvm/gos/go1.4.2/src/net/fd_poll_runtime.go:84 +0x47
net.(*pollDesc).WaitRead(0xc208128140, 0x0, 0x0)
        /root/.gvm/gos/go1.4.2/src/net/fd_poll_runtime.go:89 +0x43
net.(*netFD).accept(0xc2081280e0, 0x0, 0x7f954b881cc8, 0xc20a432990)
        /root/.gvm/gos/go1.4.2/src/net/fd_unix.go:419 +0x40b
net.(*TCPListener).AcceptTCP(0xc2085b81e8, 0xc20a42ddc8, 0x0, 0x0)
        /root/.gvm/gos/go1.4.2/src/net/tcpsock_posix.go:234 +0x4e
net.(*TCPListener).Accept(0xc2085b81e8, 0x0, 0x0, 0x0, 0x0)
        /root/.gvm/gos/go1.4.2/src/net/tcpsock_posix.go:244 +0x4c
net/http.(*Server).Serve(0xc20a4a82a0, 0x7f954b884110, 0xc2085b81e8, 0x0, 0x0)
        /root/.gvm/gos/go1.4.2/src/net/http/server.go:1728 +0x92
net/http.Serve(0x7f954b884110, 0xc2085b81e8, 0x7f952bfd4140, 0xc20800c380, 0x0, 0x0)
        /root/.gvm/gos/go1.4.2/src/net/http/server.go:1606 +0xa1
github.com/influxdb/influxdb/services/httpd.(*Service).serve(0xc20808f780)
        /root/.gvm/pkgsets/go1.4.2/global/src/github.com/influxdb/influxdb/services/httpd/service.go:83 +0x79
created by github.com/influxdb/influxdb/services/httpd.(*Service).Open
        /root/.gvm/pkgsets/go1.4.2/global/src/github.com/influxdb/influxdb/services/httpd/service.go:51 +0x283

goroutine 58 [select, 1 minutes]:
github.com/influxdb/influxdb/services/retention.(*Service).deleteShardGroups(0xc208044840)
        /root/.gvm/pkgsets/go1.4.2/global/src/github.com/influxdb/influxdb/services/retention/service.go:67 +0x433
created by github.com/influxdb/influxdb/services/retention.(*Service).Open
        /root/.gvm/pkgsets/go1.4.2/global/src/github.com/influxdb/influxdb/services/retention/service.go:44 +0x67

goroutine 59 [select, 1 minutes]:
github.com/influxdb/influxdb/services/retention.(*Service).deleteShards(0xc208044840)
        /root/.gvm/pkgsets/go1.4.2/global/src/github.com/influxdb/influxdb/services/retention/service.go:101 +0x821
created by github.com/influxdb/influxdb/services/retention.(*Service).Open
        /root/.gvm/pkgsets/go1.4.2/global/src/github.com/influxdb/influxdb/services/retention/service.go:45 +0x81

goroutine 60 [chan receive, 1 minutes]:
github.com/influxdb/influxdb/cmd/influxd/run.(*Server).startServerReporting(0xc20802e000)
        /root/.gvm/pkgsets/go1.4.2/global/src/github.com/influxdb/influxdb/cmd/influxd/run/server.go:341 +0x5e
created by github.com/influxdb/influxdb/cmd/influxd/run.func·003
        /root/.gvm/pkgsets/go1.4.2/global/src/github.com/influxdb/influxdb/cmd/influxd/run/server.go:303 +0xd78

goroutine 61 [select, 1 minutes]:
github.com/influxdb/influxdb/cmd/influxd/run.(*Command).monitorServerErrors(0xc208044360)
        /root/.gvm/pkgsets/go1.4.2/global/src/github.com/influxdb/influxdb/cmd/influxd/run/command.go:118 +0x2da
created by github.com/influxdb/influxdb/cmd/influxd/run.(*Command).Run
        /root/.gvm/pkgsets/go1.4.2/global/src/github.com/influxdb/influxdb/cmd/influxd/run/command.go:102 +0xa1a

goroutine 39 [IO wait]:
net.(*pollDesc).Wait(0xc20800ca00, 0x72, 0x0, 0x0)
        /root/.gvm/gos/go1.4.2/src/net/fd_poll_runtime.go:84 +0x47
net.(*pollDesc).WaitRead(0xc20800ca00, 0x0, 0x0)
        /root/.gvm/gos/go1.4.2/src/net/fd_poll_runtime.go:89 +0x43
net.(*netFD).Read(0xc20800c9a0, 0xc20a2b6000, 0x1000, 0x1000, 0x0, 0x7f954b881cc8, 0xc20a2da848)
        /root/.gvm/gos/go1.4.2/src/net/fd_unix.go:242 +0x40f
net.(*conn).Read(0xc20a332078, 0xc20a2b6000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
        /root/.gvm/gos/go1.4.2/src/net/net.go:121 +0xdc
net/http.(*liveSwitchReader).Read(0xc2098d44a8, 0xc20a2b6000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
        /root/.gvm/gos/go1.4.2/src/net/http/server.go:214 +0xab
io.(*LimitedReader).Read(0xc20855a480, 0xc20a2b6000, 0x1000, 0x1000, 0xc2080a3940, 0x0, 0x0)
        /root/.gvm/gos/go1.4.2/src/io/io.go:408 +0xce
bufio.(*Reader).fill(0xc20890e9c0)
        /root/.gvm/gos/go1.4.2/src/bufio/bufio.go:97 +0x1ce
bufio.(*Reader).ReadSlice(0xc20890e9c0, 0xa, 0x0, 0x0, 0x0, 0x0, 0x0)
        /root/.gvm/gos/go1.4.2/src/bufio/bufio.go:295 +0x257
bufio.(*Reader).ReadLine(0xc20890e9c0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
        /root/.gvm/gos/go1.4.2/src/bufio/bufio.go:324 +0x62
net/textproto.(*Reader).readLineSlice(0xc20a3261e0, 0x0, 0x0, 0x0, 0x0, 0x0)
        /root/.gvm/gos/go1.4.2/src/net/textproto/reader.go:55 +0x9e
net/textproto.(*Reader).ReadLine(0xc20a3261e0, 0x0, 0x0, 0x0, 0x0)
        /root/.gvm/gos/go1.4.2/src/net/textproto/reader.go:36 +0x4f
net/http.ReadRequest(0xc20890e9c0, 0xc20a483ba0, 0x0, 0x0)
        /root/.gvm/gos/go1.4.2/src/net/http/request.go:598 +0xcb
net/http.(*conn).readRequest(0xc2098d4460, 0x0, 0x0, 0x0)
        /root/.gvm/gos/go1.4.2/src/net/http/server.go:586 +0x26f
net/http.(*conn).serve(0xc2098d4460)
        /root/.gvm/gos/go1.4.2/src/net/http/server.go:1162 +0x69e
created by net/http.(*Server).Serve
        /root/.gvm/gos/go1.4.2/src/net/http/server.go:1751 +0x35e

goroutine 19 [IO wait]:
net.(*pollDesc).Wait(0xc20a056060, 0x72, 0x0, 0x0)
        /root/.gvm/gos/go1.4.2/src/net/fd_poll_runtime.go:84 +0x47
net.(*pollDesc).WaitRead(0xc20a056060, 0x0, 0x0)
        /root/.gvm/gos/go1.4.2/src/net/fd_poll_runtime.go:89 +0x43
net.(*netFD).Read(0xc20a056000, 0xc20a471000, 0x1000, 0x1000, 0x0, 0x7f954b881cc8, 0xc20a474198)
        /root/.gvm/gos/go1.4.2/src/net/fd_unix.go:242 +0x40f
net.(*conn).Read(0xc20a32e098, 0xc20a471000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
        /root/.gvm/gos/go1.4.2/src/net/net.go:121 +0xdc
net/http.(*liveSwitchReader).Read(0xc20a058048, 0xc20a471000, 0x1000, 0x1000, 0x1c00000000000000, 0x0, 0x0)
        /root/.gvm/gos/go1.4.2/src/net/http/server.go:214 +0xab
io.(*LimitedReader).Read(0xc208a57d40, 0xc20a471000, 0x1000, 0x1000, 0xc20aa21940, 0x0, 0x0)
        /root/.gvm/gos/go1.4.2/src/io/io.go:408 +0xce
bufio.(*Reader).fill(0xc208e195c0)
        /root/.gvm/gos/go1.4.2/src/bufio/bufio.go:97 +0x1ce
bufio.(*Reader).ReadSlice(0xc208e195c0, 0xa, 0x0, 0x0, 0x0, 0x0, 0x0)
        /root/.gvm/gos/go1.4.2/src/bufio/bufio.go:295 +0x257
bufio.(*Reader).ReadLine(0xc208e195c0, 0x0, 0x0, 0x0, 0xc207fd3100, 0x0, 0x0)
        /root/.gvm/gos/go1.4.2/src/bufio/bufio.go:324 +0x62
net/textproto.(*Reader).readLineSlice(0xc2082ce030, 0x0, 0x0, 0x0, 0x0, 0x0)
        /root/.gvm/gos/go1.4.2/src/net/textproto/reader.go:55 +0x9e
net/textproto.(*Reader).ReadLine(0xc2082ce030, 0x0, 0x0, 0x0, 0x0)
        /root/.gvm/gos/go1.4.2/src/net/textproto/reader.go:36 +0x4f
net/http.ReadRequest(0xc208e195c0, 0xc20a476000, 0x0, 0x0)
        /root/.gvm/gos/go1.4.2/src/net/http/request.go:598 +0xcb
net/http.(*conn).readRequest(0xc20a058000, 0x0, 0x0, 0x0)
        /root/.gvm/gos/go1.4.2/src/net/http/server.go:586 +0x26f
net/http.(*conn).serve(0xc20a058000)
        /root/.gvm/gos/go1.4.2/src/net/http/server.go:1162 +0x69e
created by net/http.(*Server).Serve
        /root/.gvm/gos/go1.4.2/src/net/http/server.go:1751 +0x35e

**Comment by majst01** [comment] 2015-06-28 11:55
Hi Bernhard,

2015/06/28 06:05:44 [INFO] snapshot: Creating new snapshot at /var/opt/influxdb/meta/snapshots/2-8388-1435471544599.tmp
panic: not implemented yet

I dont know what this means, seems you want to create a snapshot ?? but this is not implemented in InfluxDB right now.

This error does not come from influxdb-java. 
Maybe you should open a issue at influxdb with the error above.
Greetings
Stefan

**Comment by majst01** [comment] 2015-06-29 08:46
This is a known bug of influxdb 0.9.0 and should be fixed in 0.9.1-rc1 according to:

https://groups.google.com/forum/#!topic/influxdb/ePCZd0TcrnM

**Comment by majst01** [comment] 2015-07-03 14:03
Seems to be a issue with influxdb not this driver.

**Closed by majst01** 2015-07-03 14:03 UTC
